-- sequence
CREATE SEQUENCE LOG_ARCHITECT.track_id_seq START WITH 100000001 INCREMENT BY 1;

-- view
CREATE OR REPLACE VIEW LOG_ARCHITECT.V_ROMANIA_SHIPMENTS AS 
SELECT * FROM LOG_ARCHITECT.Shipment_Tracking
WHERE lat_coord BETWEEN 43 AND 49 AND long_coord BETWEEN 20 AND 30;